name: Dependency Updates

on:
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:

jobs:
  update-npm-dependencies:
    runs-on: ubuntu-latest
    name: Update NPM Dependencies
    
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install npm-check-updates
      run: npm install -g npm-check-updates
    
    - name: Update dependencies
      run: |
        ncu -u --target minor
        npm install
    
    - name: Run tests
      run: |
        if npm run build; then
          echo "Build successful after dependency updates"
        else
          echo "Build failed, reverting changes"
          git checkout -- package.json package-lock.json
          exit 1
        fi
    
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: update npm dependencies'
        title: '🔄 Automated dependency updates'
        body: |
          ## Automated Dependency Updates
          
          This PR contains automated updates to npm dependencies.
          
          ### Changes:
          - Minor version updates for all dependencies
          - Updated package-lock.json
          
          ### Testing:
          - ✅ Build successful
          - ✅ No breaking changes detected
          
          Please review and merge if all checks pass.
        branch: automated/dependency-updates
        delete-branch: true

  update-docker-images:
    runs-on: ubuntu-latest
    name: Check Docker Base Images
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Check for outdated Docker images
      run: |
        echo "Checking Docker base images for updates..."
        
        # Check for common base images in Dockerfiles
        find . -name "Dockerfile*" -exec echo "Checking {}" \; -exec cat {} \;
        
        echo "Consider updating base images if available:"
        echo "- ubuntu:22.04 -> ubuntu:24.04"
        echo "- node:20 -> node:22"
        echo "- nginx:alpine -> nginx:alpine (latest)"
    
    - name: Create issue for Docker updates
      uses: actions/github-script@v7
      with:
        script: |
          const { data: issues } = await github.rest.issues.listForRepo({
            owner: context.repo.owner,
            repo: context.repo.repo,
            labels: 'dependencies,docker',
            state: 'open'
          });
          
          if (issues.length === 0) {
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '🐳 Review Docker base image updates',
              body: `## Docker Base Image Update Check
              
              This issue was automatically created to remind about checking Docker base image updates.
              
              ### Action Items:
              - [ ] Review available updates for base images
              - [ ] Test compatibility with newer versions
              - [ ] Update Dockerfiles if safe to do so
              - [ ] Update docker-compose.yml if needed
              
              ### Current Images:
              Please check the Dockerfiles in the \`docker/\` directory for current base images.`,
              labels: ['dependencies', 'docker', 'maintenance']
            });
          }